adding error to see the behaviour v2

diff --git a/.github/workflows/basic-workflow.yaml b/.github/workflows/basic-workflow.yaml
--- a/.github/workflows/basic-workflow.yaml
+++ b/.github/workflows/basic-workflow.yaml
@@ -12,5 +12,6 @@ jobs:
       - name: i will echo ur name 
         run: echo "hello my little frind"
       - name: i will do an error 
-        run: echo "hello i will do error now"
-        run: exit 1
+        run: |
+          echo "hello i will do error now"
+          exit 1
