adding error to see the behaviour

diff --git a/.github/workflows/basic-workflow.yaml b/.github/workflows/basic-workflow.yaml
--- a/.github/workflows/basic-workflow.yaml
+++ b/.github/workflows/basic-workflow.yaml
@@ -11,4 +11,6 @@ jobs:
     steps:
       - name: i will echo ur name 
         run: echo "hello my little frind"
-        
+      - name: i will do an error 
+        run: echo "hello i will do error now"
+        run: exit 1
